version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - mba-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - ml-service
    environment:
      - ML_SERVICE_URL=http://ml-service:8000
    networks:
      - mba-network

  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"
    volumes:
      - ./ml-service:/app
      - ./ml-service/data:/app/data
    networks:
      - mba-network
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 2G

networks:
  mba-network:
    driver: bridge 